"use client";

import { useState, useCallback } from "react";
import type { RejectionResult } from "@/lib/rejection-engine";

interface Props {
  result: RejectionResult;
}

function encodeResult(result: RejectionResult): string {
  const payload = {
    o: result.opening,
    p: result.primaryReason,
    c: result.primaryCode,
    a: result.additionalReason,
    s: result.signOff,
    t: result.tier,
    tl: result.tierLabel,
    td: result.tierDescription,
    w: result.stats.wordCount,
    b: result.stats.buzzwordsFound.slice(0, 5),
  };
  try {
    return btoa(unescape(encodeURIComponent(JSON.stringify(payload))))
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=/g, "");
  } catch {
    return "";
  }
}

export default function ShareButtons({ result }: Props) {
  const [copied, setCopied] = useState(false);

  const handleCopyLink = useCallback(() => {
    const encoded = encodeResult(result);
    const url = `${window.location.origin}/results?d=${encoded}`;
    navigator.clipboard.writeText(url).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }, [result]);

  const handleLinkedIn = useCallback(() => {
    const text = [
      `Just received a ${result.tierLabel} from an ATS that never read my resume.`,
      ``,
      `Error code: ${result.primaryCode}`,
      ``,
      `"${result.opening}"`,
      ``,
      `Sharing for visibility. If this resonates, please like and subscribe to my rejection journey.`,
      ``,
      `#OpenToWork #JobSearch #Rejection #TechLayoffs #ATS`,
    ].join("\n");

    const encoded = encodeURIComponent(text);
    window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(window.location.href)}&summary=${encoded}`, "_blank", "noopener");
  }, [result]);

  const handleDownloadPDF = useCallback(async () => {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const W = 190;
    const L = 10;

    doc.setFont("courier", "bold");
    doc.setFontSize(16);
    doc.text("MegaCorp Industries\u2122", 105, 20, { align: "center" });

    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    doc.text("\u201cPeople Are Our Most Important Downsizing Opportunity\u201d", 105, 27, { align: "center" });
    doc.text("Talent Acquisition Division \u00b7 Automated Correspondence Unit", 105, 32, { align: "center" });

    doc.setLineWidth(0.5);
    doc.line(L, 36, L + W, 36);

    doc.setFontSize(10);
    doc.text(new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" }), L, 44);
    doc.text(`REF: ${result.primaryCode}`, L + W, 44, { align: "right" });

    doc.setFontSize(11);
    doc.text("Dear Valued Applicant,", L, 56);

    const bodyLines = doc.splitTextToSize(
      `${result.opening}\n\n${result.primaryReason}\n\nFurthermore: ${result.additionalReason}\n\n${result.signOff}`,
      W
    );
    doc.text(bodyLines, L, 66);

    // Red REJECTED stamp
    doc.setTextColor(200, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(52);
    doc.text("REJECTED", 105, 220, { align: "center", angle: -12 });

    doc.setTextColor(0, 0, 0);
    doc.setFont("courier", "normal");
    doc.setFontSize(7);
    doc.text(`${result.tierLabel} \u00b7 ATS Score: ${result.stats.wordCount} words processed \u00b7 Generated by Ghosted`, 105, 287, { align: "center" });

    doc.save("rejection-letter.pdf");
  }, [result]);

  return (
    <div className="space-y-3">
      <p className="text-gray-500 text-xs font-mono uppercase tracking-widest text-center">
        Share Your Experience
      </p>
      <div className="flex flex-col sm:flex-row gap-3">
        <button
          onClick={handleCopyLink}
          className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-gray-800 border-2 border-gray-600 text-gray-200 font-bold text-sm uppercase tracking-wide hover:bg-gray-700 transition-colors border-b-4 border-b-gray-900 active:border-b-2"
        >
          {copied ? "✓ Copied!" : "🔗 Copy Shareable Link"}
        </button>
        <button
          onClick={handleLinkedIn}
          className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-blue-700 border-2 border-blue-500 text-white font-bold text-sm uppercase tracking-wide hover:bg-blue-600 transition-colors border-b-4 border-b-blue-900 active:border-b-2"
        >
          💼 Share on LinkedIn
        </button>
        <button
          onClick={handleDownloadPDF}
          className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-red-800 border-2 border-red-600 text-white font-bold text-sm uppercase tracking-wide hover:bg-red-700 transition-colors border-b-4 border-b-red-900 active:border-b-2"
        >
          📄 Download PDF
        </button>
      </div>
    </div>
  );
}
